config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
]



# urlpatterns = [
#     path('', include('catalog.urls', namespace='catalog')),
#     path('admin/', admin.site.urls),
#     path('fidbeck/', include('fidbeck.urls', namespace='fidbeck')),
#     path('users/', include('users.urls', namespace='users')),
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from os import path

from django.conf.urls.static import static

from config import settings
from mailing.apps import MailingConfig
from mailing.views import Productlistview
app_name = MailingConfig.name

from django.urls import path
from mailing.views import Productlistview

urlpatterns = [
    path('', Productlistview.as_view(), name='home'),
]

users/urls.py
from django.urls import path
from django.views.generic import TemplateView

from users.apps import UsersConfig

from users.views import LoginView, LogoutView, RegisterView
# EmailVerify

app_name = UsersConfig.name

urlpatterns = [

    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    # path('verify/<str:token>/', verify_email, name='verify'),
    # path('activate/<str:token>/', activate_user, name='activate_user'),
    # path('confirm_email/', TemplateView.as_view(template_name='users/confirm_email'), name='confirm_email'),
    # path('verify_email/<uidb64>/<token>', EmailVerify.as_view(), name='verify_emaile')
]

mailing/models.py
from django.db import models

class Client(models.Model):
    email = models.EmailField()
    full_name = models.CharField(max_length=100)
    comment = models.TextField()

class Mailing(models.Model):
    send_time = models.DateTimeField()
    frequency = models.CharField(max_length=10, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')])
    status = models.CharField(max_length=10, choices=[('completed', 'Completed'), ('created', 'Created'), ('started', 'Started')])

class Message(models.Model):
    subject = models.CharField(max_length=100)
    body = models.TextField()

class MailingLog(models.Model):
    last_attempt = models.DateTimeField()
    status = models.CharField(max_length=10, choices=[('success', 'Success'), ('failure', 'Failure')])
    server_response = models.TextField()

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import Group, Permission

class User(AbstractUser):
    groups = models.ManyToManyField(Group, related_name='custom_user_set')
    user_permissions = models.ManyToManyField(Permission, related_name='custom_user_set')


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from users.models import User


class UserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

mailing/views.py
from django.views.generic import ListView






class Productlistview(ListView):
    template_name = 'mailing/home.html'

users/views.py
import secrets
from random import random
from django.conf import settings
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import CreateView
from django.core.mail import send_mail
from users.models import User
from django.contrib import messages
from users.forms import UserForm




# from users.utils import send_mail_for_verify


class LoginView(BaseLoginView):
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    pass


class RegisterView(CreateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('mailing:product_list')
    template_name = "users/register.html"



#     def form_valid(self, form):
#         new_user = form.save()
#         new_user.verification_key = secrets.randbelow(1_000_000)
#         new_user.save()
#
#         token = urlsafe_base64_encode(force_bytes(new_user.verification_key))
#         verification_url = reverse('users:verify', kwargs={'token': token})
#         send_mail(
#             subject='Регистрация на Портале.',
#             message=f'Для подтвердения регистрации, пройдите по ссылке ниже в письме. \n {self.request.build_absolute_uri(verification_url)}',
#             from_email=settings.EMAIL_HOST_USER,
#             recipient_list=[new_user.email]
#         )
#         return super().form_valid(form)
#
#
#         return super().form_valid(form)
#
#
# def verify_email(request, token):
#     try:
#         user_verification_key = urlsafe_base64_decode(token).decode()
#         user = User.objects.get(verification_key=user_verification_key)
#         if int(user_verification_key) == int(user.verification_key):
#             user.is_active = True
#             user.save()
#             messages.success(request, 'Ваш аккаунт был успешно подтвержден. Теперь вы можете войти.')
#             return redirect('mailing:product_list')
#         else:
#             messages.error(request, 'Ошибка верификации аккаунта.')
#             return HttpResponse("Ошибка верификации аккаунта.")
#     except (TypeError, ValueError, OverflowError, User.DoesNotExist):
#         messages.error(request, 'Ошибка верификации аккаунта.')
#         return HttpResponse("Ошибка верификации аккаунта.")
#
#
# def generate_password(request):
#     new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
#     request.user.set_password(new_password)
#
#     send_mail(
#         subject='Смена Пароля',
#         message=f'Ваш новый пароль \n {new_password}',
#         from_email=None,
#         recipient_list=[request.user.email]
#     )
#     request.user.save()
#     return redirect(reverse('mailing:product_list'))

mailing/templates/mailing/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Catalog</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
    <nav class="ms-5">
            <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
            <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'fidbeck:list' %}">Ваши отзывы</a>
            {% if user.is_authenticated %}
                <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выход</a>
            {% else %}
                 <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Вход</a>
                 <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
            {% endif %}
    </nav>
            </form>
        </div>
    </nav>

    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mailing/templates/mailing/home.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Садовод</h1>
    <p class="lead">Садовод - это отличный магазин для покупки овощей, фруктов, ягод</p>
</div>

<div class="container">
    <div class="row text-center">
        {% if request.user.is_authenticated %}
        <div class="col-12">
            <p>Вы уже зарегистрированы.</p>
        </div>
        {% else %}
        <div class="col-12">
            <a class="btn btn-primary" href="{% url 'registration:register' %}">Зарегистрироваться</a>
        </div>
        {% endif %}
    </div>
</div>

{% endblock %

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <form method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          <button class="btn btn-primary" type="submit">Вход</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <form method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          <button class="btn btn-primary" type="submit">Регистрация</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <form method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          <button class="btn btn-primary" type="submit">Регистрация</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}